breaking-change:
 - head-branch: ['^breaking-change', '^major-update']
bugfix:
 - head-branch: ['^fix']
documentation:
 - head-branch: ['^doc', '^docs']
miscellaneous:
 - head-branch: ['^misc']
feature:
 - head-branch: ['^feat']