"""Audit test: every PNG/GIF image referenced in docs/source/ must be either
generated by a ``doc_image:`` / ``doc_animation:`` scenario, or explicitly
listed in ``tests/doc-image-audit-exclusions.txt``.

Running
-------
.. code-block:: bash

    # Via the Makefile alias
    make doc_audit

    # Directly with pytest
    pytest tests/test_doc_audit.py

If the test fails it prints the list of untracked images so you can decide
whether to add a scenario that generates them, or add them to the exclusion
file because they are intentionally hand-crafted.

Exclusion list
--------------
``tests/doc-image-audit-exclusions.txt`` contains one repo-relative path per
line.  Lines that start with ``#`` and blank lines are ignored.  Add a path
here for any image that is deliberately *not* auto-generated by a scenario
(diagrams, logos, screenshots that cannot or need not be reproduced in
automated tests).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import pytest
import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).parent.parent
DOCS_SOURCE = REPO_ROOT / "docs" / "source"
SCENARIO_DIRS = [
    REPO_ROOT / "tests" / "visual" / "scenarios",
    REPO_ROOT / "docs" / "scenarios",
]
EXCLUSIONS_FILE = Path(__file__).parent / "doc-image-audit-exclusions.txt"

# Matches Markdown image syntax:  ![alt text](path/to/image.png)
_IMG_RE = re.compile(r"!\[.*?\]\(([^)]+)\)")

# Extensions considered "documentation images" for audit purposes.
_IMAGE_EXTS = {".png", ".gif"}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _collect_referenced_images() -> set[str]:
    """Return repo-relative paths of PNG/GIF images embedded in docs/source/ markdown files.

    Only standard Markdown image syntax (``![alt](path)``) is scanned.  URL
    fragments such as ``#only-light`` are stripped.  Absolute HTTP/HTTPS URLs
    and local HA paths (starting with ``/``) are skipped.
    """
    images: set[str] = set()
    for md_file in sorted(DOCS_SOURCE.rglob("*.md")):
        text = md_file.read_text(encoding="utf-8")
        for match in _IMG_RE.finditer(text):
            # Strip URL fragment and surrounding whitespace.
            raw = match.group(1).split("#")[0].strip()
            # Skip absolute HTTP URLs and absolute local paths.
            if raw.startswith(("http://", "https://", "//", "/")):
                continue
            # Only care about PNG/GIF files.
            if Path(raw).suffix.lower() not in _IMAGE_EXTS:
                continue
            resolved = (md_file.parent / raw).resolve()
            try:
                rel = resolved.relative_to(REPO_ROOT)
                images.add(rel.as_posix())
            except ValueError:
                pass  # outside the repo root — skip
    return images


def _collect_scenario_outputs() -> set[str]:
    """Return all ``output:`` paths declared in ``doc_image`` and ``doc_animation`` keys.

    Scans all scenario YAML files under ``tests/visual/scenarios/`` and
    ``docs/scenarios/``.  Paths are normalised to forward slashes relative to
    the repo root.
    """
    outputs: set[str] = set()
    for scenarios_dir in SCENARIO_DIRS:
        if not scenarios_dir.exists():
            continue
        for yaml_file in sorted(scenarios_dir.rglob("*.yaml")):
            with yaml_file.open(encoding="utf-8") as fh:
                data: dict[str, Any] = yaml.safe_load(fh) or {}

            # doc_image: accepts a single mapping or a list of mappings.
            raw_di = data.get("doc_image")
            if raw_di:
                entries = raw_di if isinstance(raw_di, list) else [raw_di]
                for entry in entries:
                    if isinstance(entry, dict) and "output" in entry:
                        outputs.add(entry["output"].lstrip("/"))

            # doc_animation: always a single mapping.
            raw_da = data.get("doc_animation")
            if isinstance(raw_da, dict) and "output" in raw_da:
                outputs.add(raw_da["output"].lstrip("/"))

    return outputs


def _load_exclusions() -> set[str]:
    """Return paths from the audit exclusion file (one per line; ``#`` lines ignored)."""
    if not EXCLUSIONS_FILE.exists():
        return set()
    lines = EXCLUSIONS_FILE.read_text(encoding="utf-8").splitlines()
    return {
        line.strip()
        for line in lines
        if line.strip() and not line.strip().startswith("#")
    }


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------


def test_all_doc_images_are_tracked() -> None:
    """Every PNG/GIF referenced in docs/source/ must be scenario-generated or excluded.

    To fix a failure either:

    1. Add a ``doc_image:`` or ``doc_animation:`` key to a scenario YAML so
       the image is auto-generated and verified on every CI run, **or**
    2. Add the path to ``tests/doc-image-audit-exclusions.txt`` because the
       image is intentionally hand-crafted (diagram, logo, etc.).
    """
    referenced = _collect_referenced_images()
    generated = _collect_scenario_outputs()
    excluded = _load_exclusions()

    untracked = sorted(referenced - generated - excluded)

    if untracked:
        exclusions_path = EXCLUSIONS_FILE.relative_to(REPO_ROOT)
        pytest.fail(
            f"{len(untracked)} doc image(s) are not generated by any scenario "
            f"and are not listed in {exclusions_path}.\n\n"
            "Add a doc_image:/doc_animation: key to a scenario YAML to auto-generate "
            f"each image, or add it to {exclusions_path} if it is intentionally "
            "hand-crafted:\n\n"
            + "\n".join(f"  {p}" for p in untracked)
        )
